name: My First Action

on:
  push:                    # still runs on push
  schedule:
    - cron: '0 9 * * *'   # AND also runs every day at 9am

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello Gaurav! Your GitHub Action is working!"
